--- #YAML:1.0
name:                   Read
version:                0.40
abstract:               Meta-Wrapper for reading spreadsheet data
license:                perl
author:                 
  - H.Merijn Brand <h.m.brand@xs4all.nl>
generated_by:           Author
distribution_type:      module
provides:
  Spreadsheet::Read:
    file:               Read.pm
    version:            0.40
requires:                       
  perl:                 5.006
  Exporter:             0
  Carp:                 0
  Data::Dumper:         0
configure_requires:
  ExtUtils::MakeMaker:  0
build_requires:
  perl:                 5.006
  Test::Harness:        0
  Test::More:           0.88
  Test::NoWarnings:     0
recommends:
  perl:                 5.010001
  File::Temp:           0.22
  IO::Scalar:           0
  Test::More:           0.94
resources:
  license:              http://dev.perl.org/licenses/
  repository:           http://repo.or.cz/w/Spreadsheet-Read.git
meta-spec:
  version:              1.4
  url:                  http://module-build.sourceforge.net/META-spec-v1.4.html
optional_features:
  opt_csv:
    description:        Provides parsing of CSV streams
    requires:
      Text::CSV_XS:                        0.69
    recommends:
      Text::CSV:                           1.17
      Text::CSV_PP:                        1.25
      Text::CSV_XS:                        0.73
  opt_excel:
    description:        Provides parsing of Microsoft Excel files
    requires:
      Spreadsheet::ParseExcel:             0.26
      Spreadsheet::ParseExcel::FmtDefault: 0
    recommends:
      Spreadsheet::ParseExcel:             0.57
  opt_excelx:
    description:        Provides parsing of Microsoft Excel 2007 files
    requires:
      Spreadsheet::XLSX:                   0.13
      Spreadsheet::XLSX::Fmt2007:          0
  opt_oo:
    description:        Provides parsing of OpenOffice spreadsheets
    requires:
      Spreadsheet::ReadSXC:                0.20
  opt_tools:
    description:        Spreadsheet tools
    recommends:
      Tk:                                  0
      Tk::NoteBook:                        0
      Tk::TableMatrix::Spreadsheet:        0
