--- #YAML:1.0
name:                Spreadsheet-Read
version:             0.25
abstract:            Read the data from a spreadsheet
license:             perl
author:              
    - H.Merijn Brand <h.merijn@procura.nl>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Data::Dumper:                  0
    Exporter:                      0
    File::Temp:                    0.14
    IO::Scalar:                    0
    Spreadsheet::ParseExcel:       0.26
    Spreadsheet::ReadSXC:          0.2
    Test::More:                    0
    Text::CSV:                     1
    Text::CSV_PP:                  1.05
    Text::CSV_XS:                  0.23
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
