# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Spreadsheet-Read
version:      0.03
version_from: Read.pm
installdirs:  site
requires:
    Spreadsheet::ParseExcel:       0.26
    Spreadsheet::ReadSXC:          0.12

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.28
